import React, { useState, useEffect } from 'react';
import Head from 'next/head';
import getPageComponents, { getFooter, getHeader } from '../components/req';
import BlockManager from '@/components/BlockManager';

import styles from '@/styles/Home.module.scss';

import {
  Footer,
  Header,
} from '@/components';

export default function Home() {
  const [content, setContent] = useState({})
  const [header, setHeader] = useState({})
  const [footer, setFooter] = useState({})

  useEffect(() => {
    getHeader()
      .then(({ data }) => setHeader(data.data));

    getFooter()
      .then(({ data }) => setFooter(data.data));

    getPageComponents()
      .then(({ data }) => setContent(data.data));
  }, [])

  const headContent = content?.attributes?.Content.find(item => item.__component === 'modadonna-pmu-sections.head-section')

  return (
    <>
      <Head>
        <title>PMU TOP3</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="facebook-domain-verification" content="ujp7hs78q0tqjtav1f58e58h6077ix" />
        <link rel="icon" href="/favicon.ico" />
        {/* <!-- Google Tag Manager --> */}
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
            new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
            j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
            'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
            })(window,document,'script','dataLayer','GTM-TSPTKGQ');`,
          }}></script>
        {/* <!-- End Google Tag Manager --> */}
      </Head>

      <Header header={header?.attributes} headContent={headContent} />

      <main className={styles.main}>
        <BlockManager blocks={content?.attributes?.Content} />
      </main>

      <Footer footer={footer?.attributes} />

      {/* <!-- Google Tag Manager (noscript) --> */}
      <noscript>
        <iframe
          src="https://www.googletagmanager.com/ns.html?id=GTM-TSPTKGQ"
          height="0"
          width="0"
          style={{ display: 'none', visibility: 'hidden' }}></iframe>
      </noscript>
      {/* <!-- End Google Tag Manager (noscript) --> */}
    </>
  );
}
